#!/usr/bin/env bash

set -euo pipefail

readonly APP_ID="com.tauritavern.client"
readonly IDENTITY_FILE="packaging/flatpak/build-identity.env"
readonly PNPM_CLI="flatpak-pnpm/bin/pnpm.cjs"

die() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

[[ -r "$IDENTITY_FILE" ]] ||
    die "missing build identity; invoke packaging/flatpak/build.sh"

# The file is generated by packaging/flatpak/build.sh after validating both values.
# shellcheck disable=SC1090
source "$IDENTITY_FILE"

[[ "${TAURITAVERN_BUILD_BRANCH:-}" =~ ^[A-Za-z0-9._/-]+$ ]] ||
    die "invalid TAURITAVERN_BUILD_BRANCH"
[[ "${TAURITAVERN_BUILD_REVISION:-}" =~ ^[0-9A-Fa-f]{7,64}$ ]] ||
    die "invalid TAURITAVERN_BUILD_REVISION"
[[ -r "$PNPM_CLI" ]] ||
    die "missing pinned pnpm CLI"

export TAURITAVERN_BUILD_BRANCH
export TAURITAVERN_BUILD_REVISION

mkdir -p .flatpak-bin
ln -s "../$PNPM_CLI" .flatpak-bin/pnpm
export PATH="$PWD/.flatpak-bin:$PATH"

pnpm install --offline --frozen-lockfile
cargo fetch --offline --locked --manifest-path src-tauri/Cargo.toml

rm -rf src-tauri/target/release/bundle/deb
node scripts/tauri-app.mjs --prepare-frontend build --bundles deb

mapfile -t staging_roots < <(
    find src-tauri/target/release/bundle/deb \
        -mindepth 3 \
        -maxdepth 3 \
        -type d \
        -path '*/data/usr' \
        -print
)
[[ "${#staging_roots[@]}" -eq 1 ]] ||
    die "expected exactly one Tauri DEB staging root, found ${#staging_roots[@]}"

cp -a "${staging_roots[0]}/." "$FLATPAK_DEST/"

desktop_dir="$FLATPAK_DEST/share/applications"
desktop_source="$desktop_dir/TauriTavern.desktop"
desktop_target="$desktop_dir/$APP_ID.desktop"
[[ -f "$desktop_source" ]] ||
    die "Tauri staging tree did not contain $desktop_source"
mv "$desktop_source" "$desktop_target"
sed -i "s/^Icon=tauritavern$/Icon=$APP_ID/" "$desktop_target"
grep -Fx "Icon=$APP_ID" "$desktop_target" >/dev/null ||
    die "failed to normalize the desktop icon name"

icon_root="$FLATPAK_DEST/share/icons/hicolor"
mapfile -t icons < <(find "$icon_root" -type f -path '*/apps/tauritavern.png' -print)
[[ "${#icons[@]}" -gt 0 ]] ||
    die "Tauri staging tree did not contain application icons"
for icon in "${icons[@]}"; do
    mv "$icon" "$(dirname "$icon")/$APP_ID.png"
done

if [[ -d "$icon_root/256x256@2" ]]; then
    [[ ! -e "$icon_root/256x256" ]] ||
        die "both 256x256 and 256x256@2 icon directories exist"
    mv "$icon_root/256x256@2" "$icon_root/256x256"
fi
install -Dm0644 \
    src-tauri/crates/tauritavern/icons/icon.png \
    "$icon_root/512x512/apps/$APP_ID.png"

metainfo="$FLATPAK_DEST/share/metainfo/$APP_ID.metainfo.xml"
[[ -f "$metainfo" ]] ||
    die "Tauri staging tree did not contain $metainfo"
sed -i \
    "s#<launchable type=\"desktop-id\">TauriTavern.desktop</launchable>#<launchable type=\"desktop-id\">$APP_ID.desktop</launchable>#" \
    "$metainfo"
grep -F "<launchable type=\"desktop-id\">$APP_ID.desktop</launchable>" "$metainfo" >/dev/null ||
    die "failed to normalize the AppStream launchable ID"

install -Dm0644 LICENSE "$FLATPAK_DEST/share/licenses/$APP_ID/LICENSE"

desktop-file-validate "$desktop_target"
appstreamcli validate --no-net "$metainfo"
